import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './layout.module.css';

import { CartProvider } from '../context/CartContext';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import SidebarCart from '@/components/SidebarCart/SidebarCart';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={inter.className}>
          <Header />
          <div className={styles.page}></div>
          {children}
          <Footer />

          <SidebarCart />
        </body>
      </CartProvider>
    </html>
  );
}
